{"name": "test_x[3]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 1\n +  where 1 = <bound method Random.randint of <random.Random object at 0x00000228284070A0>>(1, 3)\n +    where <bound method Random.randint of <random.Random object at 0x00000228284070A0>> = random.randint", "trace": "x = 3\n\n    @pytest.mark.parametrize('x', data)\n    def test_x(x):\n>       assert x == random.randint(1,3)\nE       assert 3 == 1\nE        +  where 1 = <bound method Random.randint of <random.Random object at 0x00000228284070A0>>(1, 3)\nE        +    where <bound method Random.randint of <random.Random object at 0x00000228284070A0>> = random.randint\n\ntest_pytest2.py:22: AssertionError"}, "parameters": [{"name": "x", "value": "3"}], "start": 1597154468232, "stop": 1597154468233, "uuid": "7bc967ca-a25f-49e4-b409-f55cc570379e", "historyId": "7b0a9ede589efe940f756a7eb1a410fc", "testCaseId": "b1db76a50f52df3788772fa82f169c41", "fullName": "test_pytest2#test_x", "labels": [{"name": "suite", "value": "test_pytest2"}, {"name": "host", "value": "lihaoil"}, {"name": "thread", "value": "8568-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest2"}]}