{"name": "test_x[2]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 == 1\n +  where 1 = <bound method Random.randint of <random.Random object at 0x00000228284070A0>>(1, 3)\n +    where <bound method Random.randint of <random.Random object at 0x00000228284070A0>> = random.randint", "trace": "x = 2\n\n    @pytest.mark.parametrize('x', data)\n    def test_x(x):\n>       assert x == random.randint(1,3)\nE       assert 2 == 1\nE        +  where 1 = <bound method Random.randint of <random.Random object at 0x00000228284070A0>>(1, 3)\nE        +    where <bound method Random.randint of <random.Random object at 0x00000228284070A0>> = random.randint\n\ntest_pytest2.py:22: AssertionError"}, "parameters": [{"name": "x", "value": "2"}], "start": 1597154468196, "stop": 1597154468197, "uuid": "c2e69342-5421-4593-98d8-e091bbbffad8", "historyId": "744c8565e78d7378dfb27b2745307ea4", "testCaseId": "b1db76a50f52df3788772fa82f169c41", "fullName": "test_pytest2#test_x", "labels": [{"name": "suite", "value": "test_pytest2"}, {"name": "host", "value": "lihaoil"}, {"name": "thread", "value": "8568-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest2"}]}