{"name": "test_xfail", "status": "skipped", "statusDetails": {"message": "Exception: 报错", "trace": "@pytest.mark.xfail\n    def test_xfail():\n>       print(er())\n\ntest_pytest9.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    def er():\n>       raise Exception('报错')\nE       Exception: 报错\n\ntest_pytest9.py:25: Exception"}, "start": 1597154468912, "stop": 1597154468912, "uuid": "ebff914a-e149-4cfe-a19b-39f6d387b56b", "historyId": "2bedbde30539568af55b45adc052a72f", "testCaseId": "d28a4b3c776dcbe8a35c7da8f6ba9f60", "fullName": "test_pytest9#test_xfail", "labels": [{"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "suite", "value": "test_pytest9"}, {"name": "host", "value": "lihaoil"}, {"name": "thread", "value": "8568-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest9"}]}